# Generated by Django 3.0.2 on 2020-02-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0003_auto_20200210_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='con_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websocket.ConnectionModel'),
        ),
    ]
